
export const products = [
  {
    id: 1,
    name: "Iphone 12 pro max",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 1199,
    offPrice: 1097,
    discount: 0,
    image: "https://s6.uupload.ir/files/12pro_max_thq8.png",
  },
  {
    id: 2,
    name: "Iphone 13 pro",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 1499,
    offPrice: 1399,
    discount: 8,
    image: "https://s6.uupload.ir/files/13pro__qzga.png",
  },
  {
    id: 3,
    name: "Iphone 13 pro max",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 1999,
    offPrice: 1899,
    discount: 10,
    image: "https://s6.uupload.ir/files/13pro_max_yaxo.png",
  },
  {
    id: 4,
    name: "Iphone x",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 999,
    offPrice: 897,
    discount: 15,
    image: "https://s6.uupload.ir/files/iphone_x_9ff.png",
  },
  {
    id: 5,
    name: "Macbook pro",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 1999,
    offPrice: 1779,
    discount: 0,
    image: "https://s6.uupload.ir/files/macbook_pro_1_yfcd.png",
  },
  {
    id: 6,
    name: "Macbook air",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 1699,
    offPrice: 1597,
    discount: 13,
    image: "https://s6.uupload.ir/files/macbook-air_j5r2.png",
  },
];
